// CHAPTER
export const RECEIVE_CHAPTERS = "RECEIVE_CHAPTERS";

// COAUTHORS
export const RECEIVE_COAUTHORS = "RECEIVE_COAUTHORS";
export const RECEIVE_AUTHORINFO = "RECEIVE_AUTHORINFO";

// COOKBOOK
export const RECEIVE_COOKBOOKS = "RECEIVE_COOKBOOKS";
export const RECEIVE_CURRENTCOOKBOOK = "RECEIVE_CURRENTCOOKBOOK";

// FAVOURITES
export const RECEIVE_MYFAVOURITES = "RECEIVE_MYFAVOURITES";
export const RECEIVE_ALLFAVOURITES = "RECEIVE_ALLFAVOURITES";

// INGREDIENTSLIST
export const RECEIVE_INGREDIENTSLIST = "RECEIVE_INGREDIENTSLIST";

// RECIPES
export const RECEIVE_RECIPES = "RECEIVE_RECIPES";
export const RECEIVE_CURRENTRECIPE = "RECEIVE_CURRENTRECIPE";

// USER
export const RECEIVE_USERINFO = "RECEIVE_USERINFO";

// STATE
export const RECEIVE_STATE = "RECEIVE_STATE";
