// CHAPTER
export const RECEIVE_CHAPTERS = "RECEIVE_CHAPTERS";

// COAUTHORS
export const RECEIVE_COAUTHORS = "RECEIVE_COAUTHORS";
export const RECEIVE_AUTHORINFO = "RECEIVE_AUTHORINFO";

// COOKBOOK
export const RECEIVE_COOKBOOKS = "RECEIVE_COOKBOOKS";
export const RECEIVE_CURRENTCOOKBOOK = "RECEIVE_CURRENTCOOKBOOK";
export const POPULATE_CURRENT_COOKBOOK = "POPULATE_CURRENT_COOKBOOK";
export const CREATE_NEW_COOKBOOK = "CREATE_NEW_COOKBOOK";
export const UPDATE_COOKBOOK_COVER = "UPDATE_COOKBOOK_COVER";

// FAVOURITES
export const RECEIVE_MYFAVOURITES = "RECEIVE_MYFAVOURITES";
export const RECEIVE_ALLFAVOURITES = "RECEIVE_ALLFAVOURITES";

// INGREDIENTSLIST
export const RECEIVE_INGREDIENTSLIST = "RECEIVE_INGREDIENTSLIST";
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";

//PHOTOS
export const IS_LIGHTBOX_VISIBLE = "IS_LIGHTBOX_VISIBLE";

// RECIPES
export const RECEIVE_RECIPES = "RECEIVE_RECIPES";
export const RECEIVE_CURRENTRECIPE = "RECEIVE_CURRENTRECIPE";
export const SEND_RECIPE_INFO = "SEND_RECIPE_INFO";
export const RECEIVE_RECIPE_PHOTOS = "RECEIVE_RECIPE_PHOTOS";
export const ADD_RECIPE_PHOTO = "ADD_RECIPE_PHOTO";

// USER
export const RECEIVE_USERINFO = "RECEIVE_USERINFO";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USERINPUT = "UPDATE_USERINPUT";

// STATE
export const RECEIVE_STATE = "RECEIVE_STATE";
