export enum ActionTypes {
    // CHAPTER
    RECEIVE_CHAPTERS,

    // COAUTHORS
    RECEIVE_COAUTHORS,
    RECEIVE_AUTHORINFO,

    // COOKBOOK
    RECEIVE_COOKBOOKS,
    RECEIVE_CURRENTCOOKBOOK,
    POPULATE_CURRENT_COOKBOOK,
    CREATE_NEW_COOKBOOK,
    UPDATE_COOKBOOK_COVER,

    // FAVOURITES
    RECEIVE_MYFAVOURITES,
    RECEIVE_ALLFAVOURITES,
    ADD_NEW_POTATO,
    REMOVE_POTATO,
    RECEIVE_POTATOES,
    RECEIVE_POTATOBUTTON,

    // INGREDIENTSLIST
    RECEIVE_INGREDIENTSLIST,
    ADD_INGREDIENT,
    DELETE_INGREDIENT,

    //INVITE
    GET_INVITE_LINK,

    //PHOTOS
    IS_LIGHTBOX_VISIBLE,

    // RECIPES
    RECEIVE_RECIPES,
    RECEIVE_CURRENTRECIPE,
    SEND_RECIPE_INFO,
    RECEIVE_RECIPE_PHOTOS,
    ADD_RECIPE_PHOTO,

    // USER
    RECEIVE_USERINFO,
    UPDATE_USER,
    UPDATE_USERINPUT,
    UPDATE_PROFILE_PIC,
    UPDATE_RECIPE_PHOTO,

    // STATE
    RECEIVE_STATE,
}
